# Generated by Django 5.0.6 on 2024-05-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('titles_won', models.IntegerField()),
                ('year_founded', models.IntegerField()),
                ('name_initials', models.CharField(max_length=4)),
            ],
        ),
    ]
