# Generated by Django 5.0.6 on 2024-05-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name_initials',
        ),
        migrations.RemoveField(
            model_name='team',
            name='titles_won',
        ),
    ]
