# Generated by Django 5.0.6 on 2024-05-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamInfo', '0002_remove_team_name_initials_remove_team_titles_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='title',
        ),
    ]
